export const SOLAR_JOURNAL = [
  {
    slug: 'how-rooftop-solar-works-in-india',
    href: '/blog/how-rooftop-solar-works-in-india',
    title: 'How rooftop solar works in India',
    category: 'Solar basics',
    date: 'Reference guide',
    image: 'https://www.jsentsolar.in/assets/images/domestic-solar.jpeg',
    excerpt: 'A practical guide to panels, inverters, net metering and the parts that determine how a rooftop system performs.',
    source: 'MNRE rooftop solar guidance',
    sourceUrl: 'https://mnre.gov.in/',
    sections: [
      { heading: 'The energy journey', body: 'Solar panels convert sunlight into DC electricity. The inverter converts that DC electricity into AC power for appliances, while the home uses solar power before drawing any remaining requirement from the grid.' },
      { heading: 'What happens to surplus power', body: 'When the system produces more electricity than the site is using, an on-grid system exports the surplus through a bidirectional meter. Imported and exported units are then recorded for settlement under the local DISCOM rules.' },
      { heading: 'What determines system size', body: 'The right size depends on your monthly consumption, available shadow-free roof area, roof orientation, sanctioned load, budget and whether you want to offset most of your annual bill or only a portion of it.' },
      { heading: 'What to check in a quotation', body: 'Ask for the proposed capacity, annual generation estimate, panel and inverter models, structure specification, protections, earthing, net-metering scope, warranties and the assumptions used for the savings estimate.' },
    ],
  },
  {
    slug: 'pm-surya-ghar-subsidy-homeowner-checklist',
    href: '/blog/pm-surya-ghar-subsidy-homeowner-checklist',
    title: 'PM Surya Ghar subsidy: what homeowners should prepare',
    category: 'Subsidy',
    date: 'Updated with official sources',
    image: 'https://www.jsentsolar.in/assets/images/pm%20saurya%20ghar.png',
    excerpt: 'The documents, eligibility questions and vendor coordination steps homeowners should understand before applying.',
    source: 'PM Surya Ghar official portal',
    sourceUrl: 'https://pmsuryaghar.gov.in/',
    sections: [
      { heading: 'Start with the electricity connection', body: 'Keep the latest electricity bill and consumer number ready. The applicant, meter and property details should be consistent across the application and the installation paperwork.' },
      { heading: 'Check the roof and load', body: 'A vendor should confirm that the roof has usable shadow-free area, suitable structural condition and enough sanctioned load for the proposed system. These checks prevent avoidable changes after registration.' },
      { heading: 'Keep the paperwork together', body: 'Depending on the DISCOM process, you may need identity and address details, electricity account information, bank details and installation or inspection documents. Confirm the current checklist on the official portal before submitting.' },
      { heading: 'Treat subsidy as a process', body: 'Subsidy timing depends on portal registration, vendor action, installation, inspection and DISCOM or agency approval. Your quotation should clearly state which steps the installer handles and which actions remain with you.' },
    ],
  },
  {
    slug: 'why-mounting-structure-quality-matters',
    href: '/blog/why-mounting-structure-quality-matters',
    title: 'Why mounting structure quality matters',
    category: 'Engineering',
    date: 'Field note',
    image: 'https://www.jsentsolar.in/assets/images/industrial-solar.jpg',
    excerpt: 'Wind exposure, corrosion protection, roof attachment and service access all matter as much as the module name on the quotation.',
    source: 'IS and MNRE guidance should be checked for each project',
    sourceUrl: 'https://mnre.gov.in/',
    sections: [
      { heading: 'The structure carries the system', body: 'Panels are only as reliable as the structure supporting them. The design must account for wind, panel layout, roof condition, drainage and the loads transferred into the building.' },
      { heading: 'Corrosion protection is practical protection', body: 'Hot-dip galvanising or an appropriate aluminium system helps protect exposed steel from moisture and corrosion. Fasteners, cut edges and dissimilar-metal contact deserve attention too.' },
      { heading: 'Roof attachment needs care', body: 'A good installation avoids unnecessary roof damage, protects waterproofing and uses an attachment method suited to the roof material. The installer should explain how penetrations are sealed and inspected.' },
      { heading: 'Leave room for service', body: 'Safe walkways, cable routing, drainage clearance and access to junction boxes make cleaning, inspection and future repairs easier. A dense layout is not automatically a better layout.' },
    ],
  },
]
