'use client'
import { useEffect, useState } from 'react'
import { Plus, UserRound } from 'lucide-react'
import { Toaster, toast } from 'sonner'
import AdminShell from '@/components/admin/AdminShell'
import { adminFetch } from '@/lib/admin-auth'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'

export default function AdminCustomers() {
  const [items, setItems] = useState([]); const [form, setForm] = useState({ name: '', email: '', phone: '', password: '' }); const [update, setUpdate] = useState({ title: '', description: '', status: 'pending' }); const [selected, setSelected] = useState(null); const [loading, setLoading] = useState(true)
  const load = async () => { try { const response = await adminFetch('/api/admin/customers'); const data = await response.json(); if (data.ok) setItems(data.items || []) } catch {} finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const create = async event => { event.preventDefault(); try { const response = await adminFetch('/api/admin/customers', { method: 'POST', body: JSON.stringify(form) }); const data = await response.json(); if (!data.ok) throw new Error(data.error); toast.success('Customer portal created'); setForm({ name: '', email: '', phone: '', password: '' }); load() } catch (error) { toast.error(error.message || 'Could not create portal') } }
  const addUpdate = async event => { event.preventDefault(); if (!selected) return; try { const response = await adminFetch(`/api/admin/customers/${selected.id}/updates`, { method: 'POST', body: JSON.stringify(update) }); const data = await response.json(); if (!data.ok) throw new Error(); toast.success('Project update added'); setUpdate({ title: '', description: '', status: 'pending' }); load() } catch { toast.error('Could not add update') } }
  return <AdminShell title="Customer Portals" subtitle="Create access and publish project progress updates"><Toaster position="top-center" richColors /><div className="grid gap-6 xl:grid-cols-[360px_1fr]"><form onSubmit={create} className="h-fit space-y-4 rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2 font-semibold text-[#0f2447]"><Plus className="h-4 w-4" /> Create portal</div><Input required placeholder="Customer name" value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} /><Input required type="email" placeholder="Customer email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} /><Input placeholder="Phone number" value={form.phone} onChange={event => setForm({ ...form, phone: event.target.value })} /><Input required minLength={8} type="password" placeholder="Temporary password" value={form.password} onChange={event => setForm({ ...form, password: event.target.value })} /><Button className="w-full bg-[#0f2447] text-white">Create customer access</Button><p className="text-xs leading-relaxed text-slate-500">Share the temporary password securely. The customer signs in at /customer/login.</p></form><div className="space-y-4">{loading ? <div className="p-8 text-center text-slate-500">Loading…</div> : items.length === 0 ? <div className="rounded-xl border border-slate-200 bg-white p-8 text-center text-slate-500"><UserRound className="mx-auto mb-2 h-6 w-6" />No customer portals yet.</div> : items.map(item => <div key={item.id} className={`rounded-xl border bg-white p-5 ${selected?.id === item.id ? 'border-emerald-400' : 'border-slate-200'}`}><button onClick={() => setSelected(item)} className="text-left"><div className="font-semibold text-[#0f2447]">{item.phone || 'Customer portal'}</div><div className="text-xs text-slate-500">{item.status} · {item.project_updates?.length || 0} updates</div></button>{selected?.id === item.id && <form onSubmit={addUpdate} className="mt-4 space-y-3 border-t border-slate-100 pt-4"><Input required placeholder="Update title" value={update.title} onChange={event => setUpdate({ ...update, title: event.target.value })} /><Textarea required placeholder="What should the customer know?" value={update.description} onChange={event => setUpdate({ ...update, description: event.target.value })} /><select className="h-10 w-full rounded-md border border-slate-200 px-3 text-sm" value={update.status} onChange={event => setUpdate({ ...update, status: event.target.value })}><option value="pending">Pending</option><option value="in_progress">In progress</option><option value="complete">Complete</option></select><Button className="bg-[#0f2447] text-white">Publish update</Button></form>}</div>)}</div></div></AdminShell>
}
